export const VehicleType = {
    OTHER: 'OTHER',
};

export const WarrantGroupStatus = {
    INITIAL: 'INITIAL',
    CALCULATION: 'CALCULATION',
    CLOSED: 'CLOSED'
};

export const WarrantStatus = {
    NEW: 'NEW',
    APPROVING: 'APPROVING',
    APPROVING_ADVANCE_PAYMENT: 'APPROVING_ADVANCE_PAYMENT',
    ADVANCE_IN_PAYMENT: 'ADVANCE_IN_PAYMENT',
    CALCULATION_EDIT: 'CALCULATION_EDIT',
    APPROVING_CALCULATION: 'APPROVING_CALCULATION',
    APPROVING_CALCULATION_PAYMENT: 'APPROVING_CALCULATION_PAYMENT',
    CALCULATION_IN_PAYMENT: 'CALCULATION_IN_PAYMENT',
    ADVANCE_REFUND: 'ADVANCE_REFUND',
    CLOSED: 'CLOSED',
    CANCELLED: 'CANCELLED',
};

export const travelType = {
    DOMESTIC: 'DOMESTIC',
    INTERNATIONAL: 'INTERNATIONAL'
};

export const PATH_URI = '/travel-warrants/public/api/';